force-app/main/default/objects/Delivery_Track__c/Delivery_Track__c.object-meta.xml
<CustomObject>
    <label>Delivery Track</label>
    <nameField>
        <label>Delivery Track Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DeliveryTracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Track__c/fields/Expected_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Expected_Delivery__c</fullName>
    <label>Expected Delivery</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Track__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>DeliveryTracks</relationshipLabel>
    <relationshipName>DeliveryTracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Track__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PENDING PICKUP</fullName>
            </value>
            <value>
                <fullName>PICKUP DONE</fullName>
            </value>
            <value>
                <fullName>IN-TRANSIT</fullName>
            </value>
            <value>
                <fullName>OUT FOR DELIVERY</fullName>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>picked up</fullName>
            </value>
            <value>
                <fullName>in transit</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>UNDELIVERED</fullName>
            </value>
            <value>
                <fullName>picked up1</fullName>
            </value>
            <value>
                <fullName>rto in transit</fullName>
            </value>
            <value>
                <fullName>rto undelivered</fullName>
            </value>
            <value>
                <fullName>misrouted</fullName>
            </value>
            <value>
                <fullName>out of delivery area</fullName>
            </value>
            <value>
                <fullName>rto out for delivery</fullName>
            </value>
            <value>
                <fullName>rto processing</fullName>
            </value>
            <value>
                <fullName>shortage</fullName>
            </value>
            <value>
                <fullName>reached at origin</fullName>
            </value>
            <value>
                <fullName>rto delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>CDLOrder</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Order_Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Delivery_Status__c</fullName>
    <label>Order Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>PENDING PICKUP</fullName>
            </value>
            <value>
                <fullName>picked up</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Manifest</fullName>
                <default>true</default>
                <label>Manifest</label>
            </value>
            <value>
                <fullName>in transit</fullName>
            </value>
            <value>
                <fullName>undelivered</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>PICKUP DONE</fullName>
            </value>
            <value>
                <fullName>picked up1</fullName>
            </value>
            <value>
                <fullName>INTRANSIT</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>NDR</fullName>
            </value>
            <value>
                <fullName>Confirmed Orders of Shopify</fullName>
            </value>
            <value>
                <fullName>rto in transit</fullName>
            </value>
            <value>
                <fullName>shortage</fullName>
            </value>
            <value>
                <fullName>rto processing</fullName>
            </value>
            <value>
                <fullName>reached at origin</fullName>
            </value>
            <value>
                <fullName>rto delivered</fullName>
            </value>
            <value>
                <fullName>misrouted</fullName>
            </value>
            <value>
                <fullName>rto out for delivery</fullName>
            </value>
            <value>
                <fullName>out of delivery area</fullName>
            </value>
            <value>
                <fullName>rto undelivered</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <externalId>true</externalId>
    <label>Order Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
                <default>true</default>
                <label>Confirm</label>
            </value>
            <value>
                <fullName>voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Track_Id__c.field-meta.xml
<CustomField>
    <fullName>Track_Id__c</fullName>
    <label>Tracking Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CDL_BatchUpdateOrderStatusTest.cls
@isTest
private class CDL_BatchUpdateOrderStatusTest {
    
    static testMethod void testBatchUpdateOrderStatus() {
        
        Order__c createOrder = new Order__c();
        createOrder.Order_Id__c = '77801128915';
        createOrder.Name = 'Test Order';
        createOrder.Track_Id__c = '77801128915';
        createOrder.Order_Delivery_Status__c = 'IN_PROGRESS';
        insert createOrder;
        
        Delivery_Track__c createDeloveryTrack = new Delivery_Track__c();
        createDeloveryTrack.Name='4905212686946';
        createDeloveryTrack.Order__c=createOrder.Id;
        createDeloveryTrack.Status__c='IN-TRANSIT';
        createDeloveryTrack.Updated_Date__c = System.now();
        createDeloveryTrack.Location__c='test address';
        createDeloveryTrack.Expected_Delivery__c = System.today();
        createDeloveryTrack.Remark__c='Trip Arrived';
        Insert createDeloveryTrack;
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Test.startTest();
        CDL_BatchUpdateOrderStatus batch = new CDL_BatchUpdateOrderStatus();
        Database.executeBatch(batch);
        Test.stopTest();
        
     
		CDL_BatchUpdateOrderStatus b = new CDL_BatchUpdateOrderStatus();
        Datetime now = Datetime.now();
        Datetime nextRunTime = now.addMinutes(30);
        String cronExp = '' + nextRunTime.second() + ' ' + nextRunTime.minute() + ' ' + nextRunTime.hour() + ' ' + nextRunTime.day() + ' ' + nextRunTime.month() + ' ? ' + nextRunTime.year();
        System.schedule('ShipDelight Update Order Status', cronExp, b );    
		
    }
    
    public class MockHttpResponseGenerator implements HttpCalloutMock 
    {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json;charset=UTF-8');
            String jsonData = '{"data":{"success":true,"error":false,"response":[{"awbno":"77801128915","orderno":"2726","ordertype":"FORWARD","shipment_latest_status_code":"753","shipment_latest_status":"DELIVERED","edd":"2023-09-23","scan_detail":[{"awbno":"77801128915","orderno":"2726","status":"PENDING PICKUP","status_code":"454","updated_date":"2023-09-18 12:52:00","location":"SURAT","exp_delivery":"2023-09-23","reason_code":"PENDING PICKUP","remarks":"Online shipment booked"}]}]}}';
            res.setBody(jsonData);
            res.setStatusCode(200);
            return res;
        }
    }
}