force-app/main/default/objects/Delivery_Track__c/Delivery_Track__c.object-meta.xml
<CustomObject>
    <label>Delivery Track</label>
    <nameField>
        <label>Delivery Track Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DeliveryTracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Track__c/fields/Expected_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Expected_Delivery__c</fullName>
    <label>Expected Delivery</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Track__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>DeliveryTracks</relationshipLabel>
    <relationshipName>DeliveryTracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Track__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PENDING PICKUP</fullName>
            </value>
            <value>
                <fullName>PICKUP DONE</fullName>
            </value>
            <value>
                <fullName>IN-TRANSIT</fullName>
            </value>
            <value>
                <fullName>OUT FOR DELIVERY</fullName>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>picked up</fullName>
            </value>
            <value>
                <fullName>in transit</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>UNDELIVERED</fullName>
            </value>
            <value>
                <fullName>picked up1</fullName>
            </value>
            <value>
                <fullName>rto in transit</fullName>
            </value>
            <value>
                <fullName>rto undelivered</fullName>
            </value>
            <value>
                <fullName>misrouted</fullName>
            </value>
            <value>
                <fullName>out of delivery area</fullName>
            </value>
            <value>
                <fullName>rto out for delivery</fullName>
            </value>
            <value>
                <fullName>rto processing</fullName>
            </value>
            <value>
                <fullName>shortage</fullName>
            </value>
            <value>
                <fullName>reached at origin</fullName>
            </value>
            <value>
                <fullName>rto delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>CDLOrder</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Last_Delivery_Status_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Delivery_Status_Change_Date__c</fullName>
    <label>Last Delivery Status Change Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Delivery_Status__c</fullName>
    <label>Order Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>PENDING PICKUP</fullName>
            </value>
            <value>
                <fullName>picked up</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Manifest</fullName>
                <default>true</default>
                <label>Manifest</label>
            </value>
            <value>
                <fullName>in transit</fullName>
            </value>
            <value>
                <fullName>undelivered</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>PICKUP DONE</fullName>
            </value>
            <value>
                <fullName>picked up1</fullName>
            </value>
            <value>
                <fullName>INTRANSIT</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>NDR</fullName>
            </value>
            <value>
                <fullName>Confirmed Orders of Shopify</fullName>
            </value>
            <value>
                <fullName>rto in transit</fullName>
            </value>
            <value>
                <fullName>shortage</fullName>
            </value>
            <value>
                <fullName>rto processing</fullName>
            </value>
            <value>
                <fullName>reached at origin</fullName>
            </value>
            <value>
                <fullName>rto delivered</fullName>
            </value>
            <value>
                <fullName>misrouted</fullName>
            </value>
            <value>
                <fullName>rto out for delivery</fullName>
            </value>
            <value>
                <fullName>out of delivery area</fullName>
            </value>
            <value>
                <fullName>rto undelivered</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <externalId>true</externalId>
    <label>Order Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
                <default>true</default>
                <label>Confirm</label>
            </value>
            <value>
                <fullName>voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Track_Id__c.field-meta.xml
<CustomField>
    <fullName>Track_Id__c</fullName>
    <label>Tracking Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Shopify_Data__c/Shopify_Data__c.object-meta.xml
<CustomObject>
    <label>Shopify Data</label>
    <nameField>
        <label>Shopify Order Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ShopifyDatas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shopify_Data__c/fields/Response_Data__c.field-meta.xml
<CustomField>
    <fullName>Response_Data__c</fullName>
    <label>Response Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CDL_BatchUpdateOrderStatus.cls
global class CDL_BatchUpdateOrderStatus implements Database.Batchable<sObject>,Schedulable,Database.AllowsCallouts {
    
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        List<AsyncApexJob> listAA=[Select Id, Status,ApexClassId,ApexClass.Name, NumberOfErrors, 
                                   JobItemsProcessed,TotalJobItems, ExtendedStatus 
                                   From AsyncApexJob 
                                   Where ApexClass.Name='CDL_BatchUpdateOrderStatus'
                                   And Status in ('Holding','Processing')];
        if(listAA.size()>0){
            return Database.getQueryLocator([SELECT Id,Order_Id__c,Name,Track_Id__c,Last_Delivery_Status_Change_Date__c,Order_Delivery_Status__c FROM order__c
                                             where Track_Id__c !=null and Order_Delivery_Status__c != 'DELIVERED'  Limit 0]); 
        }
        return Database.getQueryLocator([SELECT Id,Order_Id__c,Name,Track_Id__c,Last_Delivery_Status_Change_Date__c,Order_Delivery_Status__c FROM order__c
                                         where Track_Id__c !=null and Order_Delivery_Status__c != 'DELIVERED'  Limit 50000]);
    }
    global void execute(Database.BatchableContext bc, List<order__c> scope)
    {
        Map<String,String> updateOrderStatus = new Map<String,String>();
        Map<String,String>TrackIdandOrderIdMap = new Map<String,String>();
        
        for(order__c gettrackId : scope)
        {                          
            TrackIdandOrderIdMap.put(gettrackId.Track_Id__c,gettrackId.Id);           
        }
        
        String trackingIds = String.join(TrackIdandOrderIdMap.keySet(), ',');
        String ResponseBody = getorderStatus(trackingIds);
        if(String.isNotBlank(ResponseBody))
        {            
            map<String,object> jsonbody = (map<String,object>)json.deserializeuntyped(ResponseBody);
            Map<String, Object> dataObject = (Map<String, Object>) jsonBody.get('data');
            List<object> responseList = (List<object>)dataObject.get('response');
            List<String> existingDeliveryTracks = new List<String>();
            
            for(Delivery_Track__c deliverytrack : [SELECT Id,Name, Order__c, Status__c, Updated_Date__c, Location__c, Expected_Delivery__c, Remark__c FROM Delivery_Track__c  Limit 50000])
            {
                String trackIdandDateTime = String.valueof(deliverytrack.Updated_Date__c) +' '+ deliverytrack.Name +' '+deliverytrack.Remark__c;
                existingDeliveryTracks.add(trackIdandDateTime);
            }              
            List<Delivery_Track__c> deliveryTrackList = new List<Delivery_Track__c>();            
            if(existingDeliveryTracks.Size() >0)
            {             
                for(Object rob: responseList)
                {
                    Map<String,Object> orderMap = (Map<String,Object>) rob;                 
                    List<Object> scanDetailList = (List<Object>) orderMap.get('scan_detail');
                    updateOrderStatus.put((String) orderMap.get('awbno'),(String) orderMap.get('shipment_latest_status'));
                    for(Object sob: scanDetailList)
                    {	
                        Map<String, Object> scanDetailMap = (Map<String, Object>) sob;
                        String trackIdandDateTime = (String) scanDetailMap.get('updated_date') +' '+ (String) scanDetailMap.get('awbno')+' '+(String) scanDetailMap.get('remarks');
                        if(!existingDeliveryTracks.contains(trackIdandDateTime))
                        {
                            Delivery_Track__c createDeliveryTrack = new Delivery_Track__c();
                            if(String.isNotBlank((String) scanDetailMap.get('awbno')))
                            {
                                //String[] parts = TrackIdandOrderIdMap.get((String) scanDetailMap.get('awbno')).split(' ');                                                           
                                createDeliveryTrack.Name = (String) scanDetailMap.get('awbno'); 
                                createDeliveryTrack.Order__c = TrackIdandOrderIdMap.get((String) scanDetailMap.get('awbno'));
                                //createDeliveryTrack.OwnerId = parts[1];                         
                            }
                            if(String.isNotBlank((String) scanDetailMap.get('status')))
                            {
                                createDeliveryTrack.Status__c = (String) scanDetailMap.get('status');
                            }
                            if(String.isNotBlank((String) scanDetailMap.get('updated_date')))
                            {
                                createDeliveryTrack.Updated_Date__c = Datetime.valueOf((String) scanDetailMap.get('updated_date'));
                            }
                            if(String.isNotBlank((String) scanDetailMap.get('location')))
                            {
                                createDeliveryTrack.Location__c = (String) scanDetailMap.get('location');
                            }
                            if(String.isNotBlank((String) scanDetailMap.get('exp_delivery')))
                            {
                                createDeliveryTrack.Expected_Delivery__c = Date.valueOf((String) scanDetailMap.get('exp_delivery'));
                            }
                            if(String.isNotBlank((String) scanDetailMap.get('remarks')))
                            {
                                createDeliveryTrack.Remark__c = (String) scanDetailMap.get('remarks');
                            }
                            deliveryTrackList.add(createDeliveryTrack);
                        }                                
                    }
                    
                }
                Insert deliveryTrackList;
                
                //Update Dilivery Status on Order Object
                for(order__c gettrackId : scope)
                {
                    gettrackId.Order_Delivery_Status__c = updateOrderStatus.get(gettrackId.Track_Id__c);
                    gettrackId.Last_Delivery_Status_Change_Date__c=DateTime.valueof(DateTime.now().format('yyyy-MM-dd hh:mm:ss'));//DateTime.now();
                }
                Update scope;    
            } 
        }     
    }
    global void finish(Database.BatchableContext bc)
    {
        
    }
    public void execute(SchedulableContext sc) 
    {    
        CDL_BatchUpdateOrderStatus b = new CDL_BatchUpdateOrderStatus();
        database.executebatch(b);
        
    }   
    
    global static String getorderStatus(String trackingIds)
    {
        String api_key = System.Label.instashipinAPIKey;
        String endpointUrl = 'https://api.instashipin.com/api/ilogix/track?api_key=' + api_key
            + '&airwaybilno=' + trackingIds;
        
        System.debug('endpointUrl:: '+endpointUrl);      
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint(endpointUrl);
        req.setMethod('GET');
        req.setTimeout(120000);
        try{
            HttpResponse res = h.send(req);
            System.debug('response data: '+res.getBody());
            map<String,object> jsonbody = (map<String,object>)json.deserializeuntyped(res.getBody());
            Map<String, Object> dataObject = (Map<String, Object>) jsonBody.get('data'); 
            boolean error = boolean.valueof(dataObject.get('error'));
            
            if((res.getStatusCode() == 200 || res.getStatusCode() == 201) && error != true)
            {
                return res.getBody();   
            }else
            {
                return null;
            }
        }catch(Exception e){
            Shopify_Data__c  createResponseRecord = new Shopify_Data__c();
            createResponseRecord.Name = 'Batch Failed CDL_BatchUpdateOrderStatus';
            createResponseRecord.Error_Log__c  = 'Line No: '+e.getLineNumber()+' '+ e.getMessage();
            //createResponseRecord.Response_Data__c = e.getMessage();
            Insert createResponseRecord;
            return null;          
        }
    }
}