force-app/main/default/objects/Delivery_Track__c/Delivery_Track__c.object-meta.xml
<CustomObject>
    <label>Delivery Track</label>
    <nameField>
        <label>Delivery Track Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DeliveryTracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Track__c/fields/Expected_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Expected_Delivery__c</fullName>
    <label>Expected Delivery</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Track__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>DeliveryTracks</relationshipLabel>
    <relationshipName>DeliveryTracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Track__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PENDING PICKUP</fullName>
            </value>
            <value>
                <fullName>PICKUP DONE</fullName>
            </value>
            <value>
                <fullName>IN-TRANSIT</fullName>
            </value>
            <value>
                <fullName>OUT FOR DELIVERY</fullName>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>picked up</fullName>
            </value>
            <value>
                <fullName>in transit</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>UNDELIVERED</fullName>
            </value>
            <value>
                <fullName>picked up1</fullName>
            </value>
            <value>
                <fullName>rto in transit</fullName>
            </value>
            <value>
                <fullName>rto undelivered</fullName>
            </value>
            <value>
                <fullName>misrouted</fullName>
            </value>
            <value>
                <fullName>out of delivery area</fullName>
            </value>
            <value>
                <fullName>rto out for delivery</fullName>
            </value>
            <value>
                <fullName>rto processing</fullName>
            </value>
            <value>
                <fullName>shortage</fullName>
            </value>
            <value>
                <fullName>reached at origin</fullName>
            </value>
            <value>
                <fullName>rto delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>CDLOrder</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Last_Delivery_Status_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Delivery_Status_Change_Date__c</fullName>
    <label>Last Delivery Status Change Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Delivery_Status__c</fullName>
    <label>Order Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>PENDING PICKUP</fullName>
            </value>
            <value>
                <fullName>picked up</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Manifest</fullName>
                <default>true</default>
                <label>Manifest</label>
            </value>
            <value>
                <fullName>in transit</fullName>
            </value>
            <value>
                <fullName>undelivered</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>PICKUP DONE</fullName>
            </value>
            <value>
                <fullName>picked up1</fullName>
            </value>
            <value>
                <fullName>INTRANSIT</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>NDR</fullName>
            </value>
            <value>
                <fullName>Confirmed Orders of Shopify</fullName>
            </value>
            <value>
                <fullName>rto in transit</fullName>
            </value>
            <value>
                <fullName>shortage</fullName>
            </value>
            <value>
                <fullName>rto processing</fullName>
            </value>
            <value>
                <fullName>reached at origin</fullName>
            </value>
            <value>
                <fullName>rto delivered</fullName>
            </value>
            <value>
                <fullName>misrouted</fullName>
            </value>
            <value>
                <fullName>rto out for delivery</fullName>
            </value>
            <value>
                <fullName>out of delivery area</fullName>
            </value>
            <value>
                <fullName>rto undelivered</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <externalId>true</externalId>
    <label>Order Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
                <default>true</default>
                <label>Confirm</label>
            </value>
            <value>
                <fullName>voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Track_Id__c.field-meta.xml
<CustomField>
    <fullName>Track_Id__c</fullName>
    <label>Tracking Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Shopify_Data__c/Shopify_Data__c.object-meta.xml
<CustomObject>
    <label>Shopify Data</label>
    <nameField>
        <label>Shopify Order Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ShopifyDatas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shopify_Data__c/fields/Response_Data__c.field-meta.xml
<CustomField>
    <fullName>Response_Data__c</fullName>
    <label>Response Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CDL_UpdateOrderAPI.cls
@RestResource(urlMapping='/OrderStatus/*')
global without sharing class CDL_UpdateOrderAPI 
{
    global class Response
    {
        public String status; 
        public String httpStatusCode;
        public String errorMessage ;
        public Response()
        {
            status = 'SUCCESS';
            httpStatusCode = '200' ;
        }
    }    
    
    global class Request
    {
        public String awb_number ; 
        public String latest_scan_time ; 
        public String live_status ; 
        public String status ; 
        public String remark ; 
        public String location ; 
        public String edd_date ; 
        public String key;
        
    }
    
    @HttpPost 
    global static Response getRequestData() 
    {
        RestRequest reqst = Restcontext.request;
        Response res = new Response();
        RestResponse restRes = RestContext.response;
        restRes.headers.put('Content-Type','application/json');
        restRes.headers.put('Access-Control-Allow-Origin','*');
        String headerKey = reqst.headers.get('token'); 
        String reqBody = reqst.requestBody.toString();
        try{         
            String result;           
            Request req = (Request)JSON.deserialize(reqBody,Request.class);
            
            Shopify_Data__c newShopifyData = new Shopify_Data__c();
            newShopifyData.Name = 'Ithink - '+req.awb_number;
            newShopifyData.Response_Data__c = reqBody;         
            
            if(headerKey == System.label.IthingAPIKey)
            {                                  
                List<Delivery_Track__c> deliveryTrackList = new List<Delivery_Track__c>(); 
                List<order__c> orderList = [SELECT Id,Order_Id__c,Name,Track_Id__c,Order_Delivery_Status__c  FROM order__c where Track_Id__c !=null and  Track_Id__c =: req.awb_number];
                if(!orderList.isEmpty())
                {
                    Delivery_Track__c createDeliveryTrack = new Delivery_Track__c();
                    if(String.isNotBlank(req.awb_number))
                    {
                        createDeliveryTrack.Name = req.awb_number;    
                    }                    
                    createDeliveryTrack.Order__c = orderList[0].Id;
                    if(String.isNotBlank(req.status))
                    {
                        createDeliveryTrack.Status__c = req.status;
                    }
                    if(String.isNotBlank(req.latest_scan_time))
                    {
                        createDeliveryTrack.Updated_Date__c = Datetime.valueOf(req.latest_scan_time);
                    }
                    if(String.isNotBlank(req.location))
                    {
                        createDeliveryTrack.Location__c = req.location;
                    }
                    //createDeliveryTrack.Expected_Delivery__c = '';
                    if(String.isNotBlank(req.remark))
                    {
                        createDeliveryTrack.Remark__c = req.remark;
                    }
                    Insert createDeliveryTrack;       
                    //String formattedDateTime = DateTime.now().format('yyyy-MM-dd hh:mm:ss');
                    for(order__c od: orderList)
                    {
                        if(od.Order_Delivery_Status__c!= req.status){
                            od.Last_Delivery_Status_Change_Date__c=DateTime.now();
                        }
                        od.Order_Delivery_Status__c = req.status;
                    }
                    
                    //Update orderList;
                    Database.SaveResult [] updateResult = Database.update(orderList, false);
                    for (Database.SaveResult r : updateResult)
                    {
                        if (r.isSuccess())
                        {
                            res.status ='Success';
                            //res.errorMessage = 'Order has Successfully been Updated'; 
                           System.debug('Order has Successfully been Updated');
                        }
                        else
                        {
                            for (Database.Error e : r.getErrors())
                            {
                                res.status ='Error';
                                res.errorMessage = 'Order not Updated';
                                newShopifyData.Error_Log__c = 'Error: '+e.getMessage();
                                result = e.getMessage() ;
                            }
                        }
                    }
                }   
                
            } 
            else{
                res.status ='Error';
                res.errorMessage = 'Invalid Key';
                newShopifyData.Error_Log__c = 'Error: Invalid key: '+headerKey;
            }
            Insert newShopifyData;
        }catch(Exception e){
            res.status = e.getMessage();
            res.errorMessage = 'INVALID_INPUT_FORMAT:';
            res.httpStatusCode = '400';
            Shopify_Data__c newShopifyData = new Shopify_Data__c();
            newShopifyData.Name = 'Ithink Error:';
            newShopifyData.Response_Data__c = reqBody;
            newShopifyData.Error_Log__c = 'Line No: '+e.getLineNumber()+' '+e.getMessage();
            Insert newShopifyData;
        }
        return res;
    }
}