force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>CDLOrder</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Fulfillment_Status__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Status__c</fullName>
    <label>Fulfillment Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <externalId>true</externalId>
    <label>Order Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>paid</fullName>
            </value>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
                <default>true</default>
                <label>Confirm</label>
            </value>
            <value>
                <fullName>voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Track_Id__c.field-meta.xml
<CustomField>
    <fullName>Track_Id__c</fullName>
    <label>Tracking Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Tracking_Company__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Company__c</fullName>
    <label>Tracking Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shopify_Data__c/Shopify_Data__c.object-meta.xml
<CustomObject>
    <label>Shopify Data</label>
    <nameField>
        <label>Shopify Order Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ShopifyDatas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shopify_Data__c/fields/Response_Data__c.field-meta.xml
<CustomField>
    <fullName>Response_Data__c</fullName>
    <label>Response Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CDL_ShopifyUpdateOrdersWebhook.cls
@RestResource(urlMapping='/shopifyWebhookUpdate/*')
global without sharing class CDL_ShopifyUpdateOrdersWebhook {
    
    @HttpPost
    global static void receiveShopifyWebhook() {
        string data = '';
        Shopify_Data__c  createResponseRecord = new Shopify_Data__c();
        try
        {
            RestRequest req = RestContext.request;
            Blob body = req.requestBody;
            system.debug(JSON.serializePretty(body.toString()));
            data = body.toString();
            createResponseRecord.Response_Data__c  = body.toString();
            createResponseRecord.Name = 'get details for Update Order';
            orderDetailsWrapper orderDetailsWrapper = (orderDetailsWrapper)System.JSON.deserialize(body.toString(), orderDetailsWrapper.class);
            if(orderDetailsWrapper != null){
                if(orderDetailsWrapper.id != null){
                    createResponseRecord.Name = 'Update Order '+ orderDetailsWrapper.order_number;
                    Order__c objo = new Order__c();
                    List<Order__c> exist = [Select Id,Fulfillment_Status__c, Track_Id__c,Tracking_URL__c,Tracking_Company__c,Shipment_Status__c,Payment_Status__c from Order__c Where Order_Id__c =: orderDetailsWrapper.id limit 1];
                    if(exist.size()>0){
                        objo = exist[0];
                        objo.Fulfillment_Status__c =  orderDetailsWrapper.fulfillment_status;
						//objo.Status__c = orderDetailsWrapper.financial_status;
						objo.Payment_Status__c = orderDetailsWrapper.financial_status;
                        objo.Note__c = orderDetailsWrapper.note;
                        List<Fulfillments> lstline = new List<Fulfillments>();
                        if(orderDetailsWrapper.fulfillments != null){
                            if(orderDetailsWrapper.fulfillments.size()>0){
                                objo.Track_Id__c =  orderDetailsWrapper.fulfillments[0].tracking_number;
                                objo.Tracking_URL__c =  orderDetailsWrapper.fulfillments[0].tracking_url;
                                objo.Tracking_Company__c =  orderDetailsWrapper.fulfillments[0].tracking_company;
                                objo.Shipment_Status__c =  orderDetailsWrapper.fulfillments[0].shipment_status;
                            }
                        }
                        update objo;
                    }
                }
            }
            Insert createResponseRecord;
        }
        catch(Exception ex)
        {
            createResponseRecord.Name = 'Update Order fail';
            createResponseRecord.Error_Log__c  = 'Line No: '+ex.getLineNumber()+' '+ ex.getMessage();
            Insert createResponseRecord;
        }
    }
    
    public class orderDetailsWrapper{
        public string id {get;set;} 
        public String financial_status {get;set;} 
        public string fulfillment_status {get;set;}  
        public string note {get;set;} 
        public string order_number {get;set;} 
        public List<Fulfillments> fulfillments {get;set;} 
    }
    public class Fulfillments {
		public String shipment_status {get;set;} 
		public String tracking_company {get;set;} 
		public String tracking_number {get;set;} 
		public String tracking_url {get;set;} 
    }
    
}