force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>CDLOrder</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/FollowUp_Stage__c.field-meta.xml
<CustomField>
    <fullName>FollowUp_Stage__c</fullName>
    <label>FollowUp Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manifest</fullName>
                <default>true</default>
                <label>Manifest</label>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>NDR</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>No Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <formula>(Total_Price__c  +  Tax_Price__c +  Shipping_Chanrge__c ) -  Total_Discounts__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Next_FollowUp_Time__c.field-meta.xml
<CustomField>
    <fullName>Next_FollowUp_Time__c</fullName>
    <label>Next FollowUp Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Delivery_Status__c</fullName>
    <label>Order Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>PENDING PICKUP</fullName>
            </value>
            <value>
                <fullName>picked up</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Manifest</fullName>
                <default>true</default>
                <label>Manifest</label>
            </value>
            <value>
                <fullName>in transit</fullName>
            </value>
            <value>
                <fullName>undelivered</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>PICKUP DONE</fullName>
            </value>
            <value>
                <fullName>picked up1</fullName>
            </value>
            <value>
                <fullName>INTRANSIT</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>NDR</fullName>
            </value>
            <value>
                <fullName>Confirmed Orders of Shopify</fullName>
            </value>
            <value>
                <fullName>rto in transit</fullName>
            </value>
            <value>
                <fullName>shortage</fullName>
            </value>
            <value>
                <fullName>rto processing</fullName>
            </value>
            <value>
                <fullName>reached at origin</fullName>
            </value>
            <value>
                <fullName>rto delivered</fullName>
            </value>
            <value>
                <fullName>misrouted</fullName>
            </value>
            <value>
                <fullName>rto out for delivery</fullName>
            </value>
            <value>
                <fullName>out of delivery area</fullName>
            </value>
            <value>
                <fullName>rto undelivered</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Pending_Followup_Time__c.field-meta.xml
<CustomField>
    <fullName>Pending_Followup_Time__c</fullName>
    <label>Pending Followup Time</label>
    <summarizedField>Order_Follow_Up__c.Expected_Follow_Up_Time__c</summarizedField>
    <summaryFilterItems>
        <field>Order_Follow_Up__c.Status__c</field>
        <operation>equals</operation>
        <value>Pending</value>
    </summaryFilterItems>
    <summaryForeignKey>Order_Follow_Up__c.Order__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
                <default>true</default>
                <label>Confirm</label>
            </value>
            <value>
                <fullName>voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Voided.recordType-meta.xml
<RecordType>
    <fullName>Voided</fullName>
    <active>true</active>
    <label>Voided</label>
</RecordType>

force-app/main/default/objects/User/fields/Assign_Order_Above__c.field-meta.xml
<CustomField>
    <fullName>Assign_Order_Above__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Assign Order Above</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/On_Leave__c.field-meta.xml
<CustomField>
    <fullName>On_Leave__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Leave</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CDL_LeaveManagement.cls
public class CDL_LeaveManagement {
    
    @AuraEnabled
    public static String getUserList(){ 
        
        List<User> userList = [SELECT Id,Username, Name, On_Leave__c,Email, Assign_Order_Above__c  FROM User Where IsActive = true AND Profile.Name = 'Standard Platform User'];
        
        return Json.Serialize(userList);
    }
    
    @AuraEnabled
    public static Boolean updateUserStatus(String userId,Boolean leaveStatus){ 
        
        List<User> userList = [SELECT Id,Username, LastName, FirstName, Name,On_Leave__c,Profile.Name FROM User where Id =:userId ];
        if(!userList.isEmpty())
        {
            for(User us: userList){
                us.On_Leave__c = leaveStatus;
            }
            update userList;
            
          return userList[0].On_Leave__c;  
        }else{
          return false;  
        }             
    }
    
    @AuraEnabled
    public static String getUserOrderList(String userId)
    {
    	List<Order__c> orderList = [SELECT Id, Account__r.Name, Name, Pending_Followup_Time__c, FollowUp_Stage__c, Next_FollowUp_Time__c, Status__c,
                                    Order_Delivery_Status__c, Grand_Total__c From Order__c Where ownerId =:userId AND FollowUp_Stage__c != null AND
                                   FollowUp_Stage__c !='No Stage' AND Status__c != 'voided'];
        
        
        return JSON.Serialize(orderList);
    }
    
    @AuraEnabled
    public static String updateOrderOwner(String orderList){ 
    	 System.debug('orderList---'+orderList); 
         List<Order__c> updateOrderList = (List<Order__c>) JSON.deserialize(orderList,List<Order__c>.class);
		 System.debug('updateOrderList---'+updateOrderList);        
        try{ 
            CDL_AssignOrderOwner.updateOrderOwner(updateOrderList);
            return 'success';
        }catch(Exception e){
          	return 'Error '+e.getMessage();  
        } 
 
    }
    
}