force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>CDLOrder</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>OrderItem</label>
    <nameField>
        <displayFormat>CDOL-{0000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CDL_OrderNotes.cls
public class CDL_OrderNotes {
    
    @AuraEnabled
    public static String getOrderNotes(String recordId)
    {
       String Notes = '';
        for(Order__c getNotes: [Select Id,Note__c From Order__c Where Id =:recordId Limit 1])
        {      
            	Notes = getNotes.Note__c+'\n\n';
   				/*List<String> lines = getNotes.Note__c.split('\n');
    			Notes = '';
                for (String line : lines) 
                {                   
                    line = line.trim();                    
                    Notes += line + '\\n';
                }
        	System.debug('Concatenated Note: ' + Notes);*/
        }       
        return Notes;
    }
    
    @AuraEnabled
    public static String addNotes(String recordId,String addNotes)
    {
     	System.debug('comming notes'+addNotes);	
        Id userId =UserInfo.getUserId(); 
		String currentUserName = [SELECT Name FROM User WHERE Id =: userId].Name;
        List<Order__c> orderList = [Select Id,Note__c From Order__c Where Id =:recordId Limit 1];
        for(Order__c getNotes: orderList)
        { 
            String Notes;
            if(getNotes.Note__c != null)
            {
                Notes = getNotes.Note__c+'\n\n'+'Comments: '+addNotes+'\n'+'User: '+currentUserName+' '+'Time: '+DateTime.now().format('yyyy-MM-dd hh:mm:ss a');//DateTime.Now();
            }else
            {            	
				Notes = 'Comments: '+addNotes+'\n'+'User: '+currentUserName+' '+'Time: '+DateTime.now().format('yyyy-MM-dd hh:mm:ss a');//DateTime.Now();
            }
            getNotes.Note__c = Notes;
            System.debug('@@getNotes.Note__c:: '+getNotes.Note__c);
        }
        
        update orderList;
        return null;
    }
    @AuraEnabled
    public static String AttachmentList(String OrderId)
    {
        set<Id> orderitemIds = new Set<Id>();
        LIst<Order_Item__c> lstOrderItem = [select id from Order_Item__c where Order__c =: OrderId];
        if(lstOrderItem.size()>0){
            for(Order_Item__c l : lstOrderItem){
               orderitemIds.add(l.Id); 
            }
        }
        List<Attachment> AttachmentList = [select Id, ParentId, Name from Attachment  where ParentId  In : orderitemIds LIMIT 50000];

        return JSON.serialize(AttachmentList);
    }
}