force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>CDLOrder</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/FollowUp_Stage__c.field-meta.xml
<CustomField>
    <fullName>FollowUp_Stage__c</fullName>
    <label>FollowUp Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manifest</fullName>
                <default>true</default>
                <label>Manifest</label>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>NDR</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>No Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <formula>(Total_Price__c  +  Tax_Price__c +  Shipping_Chanrge__c ) -  Total_Discounts__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Last_Delivery_Status_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Delivery_Status_Change_Date__c</fullName>
    <label>Last Delivery Status Change Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Next_FollowUp_Time__c.field-meta.xml
<CustomField>
    <fullName>Next_FollowUp_Time__c</fullName>
    <label>Next FollowUp Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Delivery_Status__c</fullName>
    <label>Order Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>PENDING PICKUP</fullName>
            </value>
            <value>
                <fullName>picked up</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Manifest</fullName>
                <default>true</default>
                <label>Manifest</label>
            </value>
            <value>
                <fullName>in transit</fullName>
            </value>
            <value>
                <fullName>undelivered</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>PICKUP DONE</fullName>
            </value>
            <value>
                <fullName>picked up1</fullName>
            </value>
            <value>
                <fullName>INTRANSIT</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>NDR</fullName>
            </value>
            <value>
                <fullName>Confirmed Orders of Shopify</fullName>
            </value>
            <value>
                <fullName>rto in transit</fullName>
            </value>
            <value>
                <fullName>shortage</fullName>
            </value>
            <value>
                <fullName>rto processing</fullName>
            </value>
            <value>
                <fullName>reached at origin</fullName>
            </value>
            <value>
                <fullName>rto delivered</fullName>
            </value>
            <value>
                <fullName>misrouted</fullName>
            </value>
            <value>
                <fullName>rto out for delivery</fullName>
            </value>
            <value>
                <fullName>out of delivery area</fullName>
            </value>
            <value>
                <fullName>rto undelivered</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
                <default>true</default>
                <label>Confirm</label>
            </value>
            <value>
                <fullName>voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Follow_Up__c/Order_Follow_Up__c.object-meta.xml
<CustomObject>
    <label>Order Follow Up</label>
    <nameField>
        <displayFormat>FU - {0000}</displayFormat>
        <label>Order Follow Up  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Follow Ups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Follow_Up__c/fields/Actual_Follow_Up_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Follow_Up_Time__c</fullName>
    <label>Actual Follow Up Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order_Follow_Up__c/fields/Expected_Follow_Up_Time__c.field-meta.xml
<CustomField>
    <fullName>Expected_Follow_Up_Time__c</fullName>
    <label>Expected Follow Up Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order_Follow_Up__c/fields/Follow_Up_Order__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Order__c</fullName>
    <label>Follow Up Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Follow_Up__c/fields/FollowUp_Stage__c.field-meta.xml
<CustomField>
    <fullName>FollowUp_Stage__c</fullName>
    <label>FollowUp Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>NDR</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>in transit</fullName>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>Manifest</fullName>
                <default>true</default>
                <label>Manifest</label>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Follow_Up__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Follow Ups</relationshipLabel>
    <relationshipName>Order_Follow_Ups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Follow_Up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>On Time</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Assign_Order_Above__c.field-meta.xml
<CustomField>
    <fullName>Assign_Order_Above__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Assign Order Above</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/On_Leave__c.field-meta.xml
<CustomField>
    <fullName>On_Leave__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Leave</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Ordering__c.field-meta.xml
<CustomField>
    <fullName>Ordering__c</fullName>
    <label>Ordering</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CDL_NextFolloupBatch.cls
global class CDL_NextFolloupBatch implements Database.Batchable<sObject>,Schedulable,Database.AllowsCallouts {
    
    
    DateTime currentTime;
    Time systemCurrentTime = DateTime.now().time();
    global CDL_NextFolloupBatch(DateTime getCurrentTime){
        this.currentTime = getCurrentTime;
    }
    global CDL_NextFolloupBatch(){
        this.currentTime = dateTime.now();
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        List<AsyncApexJob> listAA=[Select Id, Status,ApexClassId,ApexClass.Name, NumberOfErrors, 
                                   JobItemsProcessed,TotalJobItems, ExtendedStatus 
                                   From AsyncApexJob 
                                   Where ApexClass.Name='CDL_NextFolloupBatch'
                                   And Status in ('Holding','Processing')];
        if(listAA.size()>0){
            return Database.getQueryLocator([SELECT Id,Name,OwnerId,Grand_Total__c,Next_FollowUp_Time__c,Last_Delivery_Status_Change_Date__c,(select id,Order__c,Status__c,FollowUp_Stage__c,Expected_Follow_Up_Time__c ,Actual_Follow_Up_Time__c,comment__c from Order_Follow_Ups__r),FollowUp_Stage__c,Order_Delivery_Status__c FROM order__c 
                                             Where FollowUp_Stage__c in ('RTO','Abandoned','Out for Delivery','NDR','Manifest')
                                             and Next_FollowUp_Time__c<=:currentTime and Next_FollowUp_Time__c!=null limit 0
                                            ]); 
        }
        
        return Database.getQueryLocator([SELECT Id,Name,OwnerId,Grand_Total__c,Next_FollowUp_Time__c,Last_Delivery_Status_Change_Date__c,(select id,Order__c,Status__c,FollowUp_Stage__c,Expected_Follow_Up_Time__c ,Actual_Follow_Up_Time__c,comment__c from Order_Follow_Ups__r),FollowUp_Stage__c,Order_Delivery_Status__c FROM order__c 
                                         Where FollowUp_Stage__c in ('RTO','Abandoned','Out for Delivery','NDR','Manifest')
                                         and Next_FollowUp_Time__c<=:currentTime and Next_FollowUp_Time__c!=null
                                        ]);
    }
    global void execute(Database.BatchableContext bc, List<order__c> orderList)
    {
        Map<Id,User> userMap = new Map<Id,User>([Select Id,Name,Username,Ordering__c,On_Leave__c,Assign_Order_Above__c from User]);
        List<Order__c> listtoUpdateOrderOwner = new List<Order__c>();
        
        List<Order__c> listOrderToUpdate = new List<Order__c>();       
        List<Order_Follow_Up__c> followUpList = new List<Order_Follow_Up__c>();
        List<Order_Follow_Up__c> updateMissedfollowUpList = new List<Order_Follow_Up__c>();
        List<String> existforllowUPList = new List<String>();
        for(order__c  order : orderList){
            DateTime nextFollowupDate=CDL_Utility.getNextFollowUpDate(order.Last_Delivery_Status_Change_Date__c, order.FollowUp_Stage__c,systemCurrentTime);
            
            for(Order_Follow_Up__c orderFollowup : order.Order_Follow_Ups__r){
                existforllowUPList.add(orderFollowup.Order__c+orderFollowup.FollowUp_Stage__c+orderFollowup.Expected_Follow_Up_Time__c);
                if(orderFollowup.Status__c=='Pending'){
                    orderFollowup.Status__c='Missed';
                    orderFollowup.comment__c='Missed';
                    orderFollowup.Actual_Follow_Up_Time__c= Datetime.now();
                    updateMissedfollowUpList.add(orderFollowup);
                }
            }
            if(!existforllowUPList.contains(order.Id+order.FollowUp_Stage__c+order.Next_FollowUp_Time__c))
            {
                Order_Follow_Up__c createFollowUp = new Order_Follow_Up__c();
                createFollowUp.Order__c = order.Id;
                createFollowUp.Expected_Follow_Up_Time__c  = order.Next_FollowUp_Time__c;
                createFollowUp.Follow_Up_Order__c= order.Order_Follow_Ups__r.size()+1; 
                createFollowUp.FollowUp_Stage__c=order.FollowUp_Stage__c;
                createFollowUp.Status__c='Pending';
                followUpList.add(createFollowUp);
            }
            If(nextFollowupDate != null)
            {
                order.Next_FollowUp_Time__c=nextFollowupDate;
            }else{
                Datetime today = Datetime.now().date();
                order.Next_FollowUp_Time__c = Datetime.newInstance(today.year(), today.month(), today.day() + 1, 11, 0, 0);
            }
                      
            listOrderToUpdate.add(order);
            if(userMap.get(order.OwnerId).On_Leave__c == true){
                listtoUpdateOrderOwner.add(order);
            }            
        }
                
        if(updateMissedfollowUpList.Size() > 0){
            update updateMissedfollowUpList;
        }
        if(followUpList.Size() > 0){
            insert followUpList;
        }
        update listOrderToUpdate;
        
        //update Owner
        if(!listtoUpdateOrderOwner.isEmpty()){
            CDL_AssignOrderOwner.updateOrderOwner(listtoUpdateOrderOwner);
        }
    }
    global void finish(Database.BatchableContext bc)
    {
        
    }
    public void execute(SchedulableContext sc) 
    {    
        CDL_NextFolloupBatch b = new CDL_NextFolloupBatch(currentTime);
        database.executebatch(b);
        
    }   
    
    
}