force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>CDLOrder</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order_Follow_Up__c/Order_Follow_Up__c.object-meta.xml
<CustomObject>
    <label>Order Follow Up</label>
    <nameField>
        <displayFormat>FU - {0000}</displayFormat>
        <label>Order Follow Up  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Follow Ups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Follow_Up__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Follow Ups</relationshipLabel>
    <relationshipName>Order_Follow_Ups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CDL_OrderFollowupTriggerHandler.cls
public class CDL_OrderFollowupTriggerHandler {
    public static void updateOrderNote(List<Order_Follow_Up__c> orderList, Map<Id,Order_Follow_Up__c> oldMap) {
        
        List<Order_Follow_Up__c> orderfollowList = new List<Order_Follow_Up__c>();
        Id userId =UserInfo.getUserId();
        String currentUserName = [SELECT Name FROM User WHERE Id =: userId].Name;
        set<Id> orderfollowlat = new set<Id>();
        List<Order__c> OrderUpd = new list<Order__c>();   
        
        if(orderList.size() > 0)
        {
            for(Order_Follow_Up__c newOrderfollow :orderList){
                Order_Follow_Up__c oldOrderfollow = (Order_Follow_Up__c)oldMap.get(newOrderfollow.Id); 
                if(oldMap.get(newOrderfollow.Id).Comment__c != newOrderfollow.Comment__c && newOrderfollow.Comment__c != null)
                {
                    orderfollowlat.add(oldOrderfollow.Id);
                }
            }
        }
        if(!orderfollowlat.isEmpty())
        {
            orderfollowList = [SELECT Id,Order__c,Comment__c,Order__r.Id,Order__r.Note__c FROM Order_Follow_Up__c where Id IN:orderfollowlat];
        }
        if(orderfollowList.size()>0){
            for(Order_Follow_Up__c OrderFollow : orderfollowList)
            {
                Order__c Ordercre = new Order__c();
                Ordercre.id = OrderFollow.Order__r.Id;
                if(OrderFollow.Comment__c != null && OrderFollow.Comment__c != 'Missed') //OrderFollow.Comment__c
                {
                    String Notes;
                    Notes = 'Comments: '+ OrderFollow.Comment__c +'\n'+'User: '+ currentUserName +' '+'Time: '+DateTime.now().format('yyyy-MM-dd hh:mm:ss a');//DateTime.Now();
                    system.debug('Notes'+Notes);
                    if(OrderFollow.Order__r.Note__c != null){
                        Ordercre.Note__c = Notes+'\n\n'+OrderFollow.Order__r.Note__c;
                    }
                    else
                    {
                        Ordercre.Note__c = Notes;
                    }
                    
                }
                OrderUpd.add(Ordercre);
                
            }    
        } 
        if (OrderUpd.size()>0){
            update OrderUpd;    
        }
    }
}