force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>CDLOrder</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Billing_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Billing_PostalCode__c</fullName>
    <label>Billing PostalCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Call__c.field-meta.xml
<CustomField>
    <fullName>Call__c</fullName>
    <label>Call</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Customer Not Received</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/FollowUp_Stage__c.field-meta.xml
<CustomField>
    <fullName>FollowUp_Stage__c</fullName>
    <label>FollowUp Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manifest</fullName>
                <default>true</default>
                <label>Manifest</label>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>NDR</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>No Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <formula>(Total_Price__c  +  Tax_Price__c +  Shipping_Chanrge__c ) -  Total_Discounts__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Initial_FollowUp_Comment__c.field-meta.xml
<CustomField>
    <fullName>Initial_FollowUp_Comment__c</fullName>
    <label>Initial FollowUp Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Next_FollowUp_Time__c.field-meta.xml
<CustomField>
    <fullName>Next_FollowUp_Time__c</fullName>
    <label>Next FollowUp Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Amount__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount__c</fullName>
    <label>Order Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Delivery_Status__c</fullName>
    <label>Order Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>PENDING PICKUP</fullName>
            </value>
            <value>
                <fullName>picked up</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Manifest</fullName>
                <default>true</default>
                <label>Manifest</label>
            </value>
            <value>
                <fullName>in transit</fullName>
            </value>
            <value>
                <fullName>undelivered</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>PICKUP DONE</fullName>
            </value>
            <value>
                <fullName>picked up1</fullName>
            </value>
            <value>
                <fullName>INTRANSIT</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>NDR</fullName>
            </value>
            <value>
                <fullName>Confirmed Orders of Shopify</fullName>
            </value>
            <value>
                <fullName>rto in transit</fullName>
            </value>
            <value>
                <fullName>shortage</fullName>
            </value>
            <value>
                <fullName>rto processing</fullName>
            </value>
            <value>
                <fullName>reached at origin</fullName>
            </value>
            <value>
                <fullName>rto delivered</fullName>
            </value>
            <value>
                <fullName>misrouted</fullName>
            </value>
            <value>
                <fullName>rto out for delivery</fullName>
            </value>
            <value>
                <fullName>out of delivery area</fullName>
            </value>
            <value>
                <fullName>rto undelivered</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>paid</fullName>
            </value>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Pending_Followup_Time__c.field-meta.xml
<CustomField>
    <fullName>Pending_Followup_Time__c</fullName>
    <label>Pending Followup Time</label>
    <summarizedField>Order_Follow_Up__c.Expected_Follow_Up_Time__c</summarizedField>
    <summaryFilterItems>
        <field>Order_Follow_Up__c.Status__c</field>
        <operation>equals</operation>
        <value>Pending</value>
    </summaryFilterItems>
    <summaryForeignKey>Order_Follow_Up__c.Order__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Shipping_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Shipping_PostalCode__c</fullName>
    <label>Shipping PostalCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
                <default>true</default>
                <label>Confirm</label>
            </value>
            <value>
                <fullName>voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <summarizedField>Order_Item__c.Subtotal_Price__c</summarizedField>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Voided.recordType-meta.xml
<RecordType>
    <fullName>Voided</fullName>
    <active>true</active>
    <label>Voided</label>
</RecordType>

force-app/main/default/objects/Order_Follow_Up__c/Order_Follow_Up__c.object-meta.xml
<CustomObject>
    <label>Order Follow Up</label>
    <nameField>
        <displayFormat>FU - {0000}</displayFormat>
        <label>Order Follow Up  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Follow Ups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Follow_Up__c/fields/Actual_Follow_Up_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Follow_Up_Time__c</fullName>
    <label>Actual Follow Up Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order_Follow_Up__c/fields/Expected_Follow_Up_Time__c.field-meta.xml
<CustomField>
    <fullName>Expected_Follow_Up_Time__c</fullName>
    <label>Expected Follow Up Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order_Follow_Up__c/fields/Follow_Up_Order__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Order__c</fullName>
    <label>Follow Up Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Follow_Up__c/fields/FollowUp_Stage__c.field-meta.xml
<CustomField>
    <fullName>FollowUp_Stage__c</fullName>
    <label>FollowUp Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>NDR</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>in transit</fullName>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>Manifest</fullName>
                <default>true</default>
                <label>Manifest</label>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Follow_Up__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Follow Ups</relationshipLabel>
    <relationshipName>Order_Follow_Ups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Follow_Up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>On Time</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>OrderItem</label>
    <nameField>
        <displayFormat>CDOL-{0000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Discounts__c.field-meta.xml
<CustomField>
    <fullName>Discounts__c</fullName>
    <label>Discounts</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Subtotal_Price__c.field-meta.xml
<CustomField>
    <fullName>Subtotal_Price__c</fullName>
    <label>Subtotal Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Tax_Price__c.field-meta.xml
<CustomField>
    <fullName>Tax_Price__c</fullName>
    <label>Tax Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Weight_gm__c.field-meta.xml
<CustomField>
    <fullName>Weight_gm__c</fullName>
    <label>Weight (gm)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CDL_LeadManagement.cls
public class CDL_LeadManagement
{
    @AuraEnabled
    public static String getOrderLit(String orderStatus,String orderDays)
    {
        String days = '';
        if (orderDays != 'All' && orderDays != 'today') {
            days = ' AND CreatedDate = LAST_N_DAYS:' + orderDays;
        }if(orderDays == 'today')
        {
            days = ' AND CreatedDate = today';
        }if(orderDays == 'yesterday')
        {
            days = ' AND CreatedDate = yesterday';
        }
        String soqlQuery = 'SELECT Id,CreatedDate, Name,Pending_Followup_Time__c,FollowUp_Stage__c ,Next_FollowUp_Time__c, Status__c, Payment_Status__c, isVerified__c, Order_Delivery_Status__c, Total_Price__c, Grand_Total__c, Order_Amount__c, Account__r.Name, Account__r.Phone__c, Billing_Street__c, Billing_City__c, Billing_State__c, Billing_PostalCode__c, Billing_Country__c, Shipping_Street__c, Shipping_City__c, Shipping_State__c, Shipping_PostalCode__c, Shipping_Country__c FROM Order__c ';
        
        if (orderStatus == 'All') {
            soqlQuery += 'WHERE Status__c != null AND Account__c != null' + days + ' ORDER BY CreatedDate DESC LIMIT 50000';
        } else if (orderStatus == 'Abandoned' || orderStatus == 'Confirm' || orderStatus == 'Voided') {
            soqlQuery += 'WHERE Status__c = \'' + orderStatus + '\' AND Account__c != null' + days + ' ORDER BY Next_FollowUp_Time__c ASC LIMIT 50000';
        } else if (orderStatus == 'Out for Delivery') {
            soqlQuery += 'WHERE Status__c = \'' + orderStatus + '\' AND Account__c != null' + days + ' ORDER BY Next_FollowUp_Time__c ASC LIMIT 50000';
        }
        
        System.debug('soqlQuery:: ' + soqlQuery);
        List<Order__c> orderList = Database.query(soqlQuery);
        System.debug('soqlQuery:: ' + orderList.size());
        return JSON.serialize(orderList);
    }
    
    @AuraEnabled
    public static String updateOrderDetails(String orderDetails)
    {
        String result;
        Map<String,Object> orderDetailsMap = (Map<String,Object>) JSON.DeserializeUntyped(orderDetails);
        
        List<Order__c> orderList = [SELECT Id,Name,Status__c,isVerified__c,Order_Delivery_Status__c,Total_Price__c,Grand_Total__c,Order_Amount__c,
                                    Account__r.name,Account__r.Phone__c,Billing_Street__c,Billing_City__c,Billing_State__c,Billing_PostalCode__c,Billing_Country__c,
                                    Shipping_Street__c,Shipping_City__c,Shipping_State__c,Shipping_PostalCode__c,Shipping_Country__c FROM Order__c where Id =:String.valueOf(orderDetailsMap.get('Id')) ];
        
        if(orderList.Size() > 0)
        {
            for(Order__c updateOrder : orderList)
            {
                updateOrder.Call__c = String.valueOf(orderDetailsMap.get('Call__c'));
                //update billing address
                updateOrder.Billing_Street__c = String.valueOf(orderDetailsMap.get('Billing_Street__c'));
                updateOrder.Billing_City__c = String.valueOf(orderDetailsMap.get('Billing_City__c'));
                updateOrder.Billing_State__c = String.valueOf(orderDetailsMap.get('Billing_State__c'));
                updateOrder.Billing_PostalCode__c = String.valueOf(orderDetailsMap.get('Billing_PostalCode__c'));
                updateOrder.Billing_Country__c = String.valueOf(orderDetailsMap.get('Billing_Country__c'));
                
                //update Shipping address
                updateOrder.Shipping_Street__c = String.valueOf(orderDetailsMap.get('Shipping_Street__c'));
                updateOrder.Shipping_City__c = String.valueOf(orderDetailsMap.get('Shipping_City__c'));
                updateOrder.Shipping_State__c = String.valueOf(orderDetailsMap.get('Shipping_State__c'));
                updateOrder.Shipping_PostalCode__c = String.valueOf(orderDetailsMap.get('Shipping_PostalCode__c'));
                updateOrder.Shipping_Country__c = String.valueOf(orderDetailsMap.get('Shipping_Country__c'));
                
            }
            
            //update orderList;
            Database.SaveResult [] updateResult = Database.update(orderList, false);
            for (Database.SaveResult r : updateResult)
            {
                if (r.isSuccess())
                {
                    result = 'Order has been Updated';
                }
                else
                {
                    for (Database.Error e : r.getErrors())
                    {
                        result = e.getMessage() ;
                    }
                }
            }
        }
        return result;
    }
    
    @AuraEnabled
    public static String verifiedOrder(String orderDetails)
    {
        String result;
        System.debug('@@orderDetails:: '+orderDetails);
        Map<String,Object> orderDetailsMap = (Map<String,Object>) JSON.DeserializeUntyped(orderDetails);
        
        List<Order__c> orderList = [SELECT Id,Name,Status__c,FollowUp_Stage__c,isVerified__c,Order_Delivery_Status__c,Total_Price__c,Grand_Total__c,Order_Amount__c,
                                    Account__r.name,Account__r.Phone__c,Billing_Street__c,Billing_City__c,Billing_State__c,Billing_PostalCode__c,Billing_Country__c,
                                    Shipping_Street__c,Shipping_City__c,Shipping_State__c,Shipping_PostalCode__c,Shipping_Country__c FROM Order__c where Id =:String.valueOf(orderDetailsMap.get('Id')) ];
        
        if(orderList.Size() > 0)
        {
            for(Order__c updateOrder : orderList)
            {
                updateOrder.isVerified__c = true;
                updateOrder.FollowUp_Stage__c = 'Verified';
            }
            //delete followup
            List<Order_Follow_Up__c> latestfollowupItem = [SELECT Id,Order__c,FollowUp_Stage__c,Actual_Follow_Up_Time__c,Expected_Follow_Up_Time__c,Status__c,Comment__c,Follow_Up_Order__c FROM Order_Follow_Up__c Where Order__c =:String.valueOf(orderDetailsMap.get('Id')) and Comment__c ='' and FollowUp_Stage__c = 'Manifest' order by createddate desc LIMIT 1];
            if(latestfollowupItem.size()>0){
                delete latestfollowupItem[0];
            }
            //update orderList;
            Database.SaveResult [] updateResult = Database.update(orderList, false);
            for (Database.SaveResult r : updateResult)
            {
                if (r.isSuccess())
                {
                    result = 'Order has been successfuly Verified';
                }
                else
                {
                    for (Database.Error e : r.getErrors())
                    {
                        result = e.getMessage() ;
                    }
                }
            }
        }
        return result;
    }
    
    @AuraEnabled
    public static String orderItemList(String OrderId)
    {
        List<Order_Item__c> orderItemList = [SELECT Id,Order__c, Product_Name__c, Subtotal_Price__c, Discounts__c, Order_Item_ID__c,
                                             Weight_gm__c, Quantity__c, Vendor__c, Tax_Price__c, List_Price__c, SKU__c, Product_Id__c FROM Order_Item__c Where Order__c =:OrderId  LIMIT 50000];
        
        return JSON.serialize(orderItemList);
    }
    @AuraEnabled
    public static String followupItemsList(String OrderId)
    {
        List<Order_Follow_Up__c> followupItemsList = [SELECT Id,Order__c,FollowUp_Stage__c,Actual_Follow_Up_Time__c,Expected_Follow_Up_Time__c,Status__c,Comment__c,Follow_Up_Order__c FROM Order_Follow_Up__c Where Order__c =:OrderId order by createddate desc LIMIT 50000];
        
        return JSON.serialize(followupItemsList);
    }
    @AuraEnabled
    public static String latestfollowupItem(String OrderId)
    {
        Order_Follow_Up__c latestfollowupItem = new Order_Follow_Up__c();        
        List<Order_Follow_Up__c> latestfollowupItemList = [SELECT Id,Order__c,FollowUp_Stage__c,Actual_Follow_Up_Time__c,Expected_Follow_Up_Time__c,Status__c,Comment__c,Follow_Up_Order__c FROM Order_Follow_Up__c Where Order__c =:OrderId order by createddate desc LIMIT 1];
        if(latestfollowupItemList.size() > 0)
        {
            return JSON.serialize(latestfollowupItemList[0]);
        }else{
            return null;    
        }
        
        
    }
    
    @AuraEnabled
    public static String UpdateFollowUpIsVerified(string folloupItemdetail,String nextFollowUpTime,Boolean intialComment)
    {
        String result;
        nextFollowUpTime = nextFollowUpTime.substring(0, nextFollowUpTime.length() - 9).replace('T', ' ');
        datetime followuptime = DateTime.valueOfGmt(nextFollowUpTime);
        Order_Follow_Up__c latestFU = (Order_Follow_Up__c)System.JSON.deserialize(folloupItemdetail, Order_Follow_Up__c.class);
        if(!intialComment){          
            Order_Follow_Up__c latestfollowupItem = [SELECT Id,Order__c,FollowUp_Stage__c,Order__r.Order_Delivery_Status__c,Actual_Follow_Up_Time__c,Expected_Follow_Up_Time__c,Status__c,Comment__c,Follow_Up_Order__c FROM Order_Follow_Up__c Where Id =:latestFU.Id order by createddate desc LIMIT 1];
            latestfollowupItem.Actual_Follow_Up_Time__c = system.Datetime.now();
            latestfollowupItem.Comment__c = latestFU.Comment__c;
            latestfollowupItem.Status__c = 'On Time';
            update  latestfollowupItem;
            
            Order__c initialfollowup = [SELECT Id,Initial_FollowUp_Comment__c,FollowUp_Stage__c,Next_FollowUp_Time__c FROM Order__c where Id =: latestFU.Order__c limit 1];  
            initialfollowup.Initial_FollowUp_Comment__c = latestFU.Comment__c;
            initialfollowup.Next_FollowUp_Time__c = followuptime;
            update  initialfollowup;
        }
        else{
            Order__c initialfollowup = [SELECT Id,Initial_FollowUp_Comment__c,FollowUp_Stage__c,Next_FollowUp_Time__c FROM Order__c where Id =: latestFU.Order__c limit 1];  
            initialfollowup.Initial_FollowUp_Comment__c = latestFU.Comment__c;
            initialfollowup.Next_FollowUp_Time__c = followuptime;
            update  initialfollowup;
        }
        return result;
    }
    
    @AuraEnabled
    public static String UpdateFollowUp(string folloupItemdetail)
    {
        String result;
        system.debug('folloupItemdetail: '+folloupItemdetail);
        //Update Current FollowUp Step
        Order_Follow_Up__c latestFU = (Order_Follow_Up__c)System.JSON.deserialize(folloupItemdetail, Order_Follow_Up__c.class);
        Order_Follow_Up__c latestfollowupItem = [SELECT Id,Order__c,Order__r.Order_Delivery_Status__c,Actual_Follow_Up_Time__c,Expected_Follow_Up_Time__c,Status__c,Comment__c,Follow_Up_Order__c FROM Order_Follow_Up__c Where Id =:latestFU.Id order by createddate desc LIMIT 1];
        latestfollowupItem.Actual_Follow_Up_Time__c = system.Datetime.now();
        latestfollowupItem.Comment__c = latestFU.Comment__c;
        if(latestfollowupItem.Expected_Follow_Up_Time__c< latestfollowupItem.Actual_Follow_Up_Time__c){
            latestfollowupItem.Status__c = 'Delayed';
        }
        else{
            latestfollowupItem.Status__c = 'On Time';
        }
        update  latestfollowupItem;
        
        //create Next FollowUp Step
        Order_Follow_Up__c obj = new Order_Follow_Up__c();
        obj.Order__c = latestfollowupItem.Order__c;
        datetime followuptime = null;        
        obj.Expected_Follow_Up_Time__c = followuptime;
        obj.Follow_Up_Order__c =  latestfollowupItem.Follow_Up_Order__c + 1;
        obj.Status__c = 'Pending';
        insert obj;
        result = latestfollowupItem.Status__c;
        return result;
    }
    
    @AuraEnabled
    public static String getAllfollowupByStatus(String OrderStatus)
    {
        List<Order_Follow_Up__c> getAllfollowupByStatus = [SELECT Id,Order__c,Order__r.Name,Actual_Follow_Up_Time__c,Expected_Follow_Up_Time__c,Status__c,Comment__c,Follow_Up_Order__c FROM Order_Follow_Up__c Where (Order__r.Order_Delivery_Status__c =:OrderStatus AND Comment__c = NULL AND Expected_Follow_Up_Time__c <= TODAY) order by createddate LIMIT 50000];
        return JSON.serialize(getAllfollowupByStatus);
    }
    
    @AuraEnabled
    public static String getnewOrderList(String orderId)
    {
        Map<String,Object> returnMap = new Map<String,Object>();
        List<Order__c> setOrderList = new  List<Order__c>();     
        returnMap.put('currentStage','');
        returnMap.put('orderList',setOrderList);
        if(String.isNotBlank(orderId) && orderId != null){
            returnMap.put('currentStage','');
            setOrderList = selectedOrderDetails(orderId);
            returnMap.put('orderList',setOrderList);
        }
        else{
            setOrderList = orderListOnPriorities('Manifest');
            if(setOrderList.size() > 0){
                returnMap.put('currentStage','Manifest');
                returnMap.put('orderList',setOrderList);           
            }
            else{
                setOrderList = orderListOnPriorities('NDR');
                if(setOrderList.size() > 0){
                    returnMap.put('currentStage','NDR');
                    returnMap.put('orderList',setOrderList);
                }
                else{
                    setOrderList = orderListOnPriorities('Out for Delivery');
                    if(setOrderList.size() > 0){
                        returnMap.put('currentStage','Out for Delivery');
                        returnMap.put('orderList',setOrderList);            
                    }
                    else{      
                        setOrderList = orderListOnPriorities('Abandoned');
                        if(setOrderList.size() > 0){
                            returnMap.put('currentStage','Abandoned');
                            returnMap.put('orderList',setOrderList);    
                        }
                        else{
                            setOrderList = orderListOnPriorities('RTO');
                            if(setOrderList.size() > 0){
                                returnMap.put('currentStage','RTO');
                                returnMap.put('orderList',setOrderList);
                            }
                        }
                    }
                }            
            }
        }
        return JSON.serialize(returnMap);
    }
    
    @AuraEnabled
    public static List<Order__c> orderListOnPriorities(String deliveryStatus)
    {
        String userId = UserInfo.getUserId();
        DateTime currentTimeMinusOneMinute = System.now();
        
        List<String> orderIds = new List<String>();
        for(Order_Follow_Up__c todayFUOnly : [SELECT Id, Order__c, FollowUp_Stage__c, Actual_Follow_Up_Time__c, Expected_Follow_Up_Time__c, Status__c, Comment__c, Follow_Up_Order__c 
                                              FROM Order_Follow_Up__c 
                                              WHERE (Comment__c = null OR Comment__c = '') 
                                              AND Expected_Follow_Up_Time__c <= :currentTimeMinusOneMinute
                                              AND Status__c = 'Pending'
                                              //AND Expected_Follow_Up_Time__c <= today  
                                              ORDER BY CreatedDate DESC 
                                              LIMIT 50000]) {
                                                  orderIds.add(todayFUOnly.Order__c); 
                                              }	
        List<Order__c> getInitialOrderList = [SELECT Id,CreatedDate, Name, Status__c, Payment_Status__c,Call__c, isVerified__c, Order_Delivery_Status__c,
                                              (SELECT Id, Status__c, Comment__c FROM Order_Follow_Ups__r), Next_FollowUp_Time__c,FollowUp_Stage__c, 
                                              Total_Price__c, Grand_Total__c, Order_Amount__c, Account__r.Name, Account__r.Phone__c, 
                                              Billing_Street__c, Billing_City__c, Billing_State__c, Billing_PostalCode__c, Billing_Country__c, 
                                              Shipping_Street__c, Shipping_City__c, Shipping_State__c, Shipping_PostalCode__c, Shipping_Country__c
                                              FROM Order__c where Account__c !=null AND ownerId =: userId
                                              AND isVerified__c != true AND Initial_FollowUp_Comment__c = null
                                              ORDER BY CreatedDate DESC LIMIT 1];
        
        List<Order__c> getFollowUpOrderList = [SELECT Id,CreatedDate, Name, Status__c,FollowUp_Stage__c,Payment_Status__c,Call__c, isVerified__c, Order_Delivery_Status__c, 
                                               Total_Price__c, Grand_Total__c, Order_Amount__c, Account__r.Name, Account__r.Phone__c, Next_FollowUp_Time__c, 
                                               Billing_Street__c, Billing_City__c, Billing_State__c, Billing_PostalCode__c, Billing_Country__c, 
                                               Shipping_Street__c, Shipping_City__c, Shipping_State__c, Shipping_PostalCode__c, Shipping_Country__c
                                               FROM Order__c where Id In : orderIds AND Account__c !=null AND ownerId =: userId
                                               AND FollowUp_Stage__c=:deliveryStatus ORDER BY CreatedDate DESC LIMIT 1];   
        
        List<Order__c> getOrderList = new List<Order__c>();    
        
        if(getInitialOrderList.Size() > 0){    
            for(Order__c getOrder: getInitialOrderList)
            {
                if (getOrder.Order_Follow_Ups__r.isEmpty()) 
                {
                    getOrderList.add(getOrder);
                }else{
                    getOrderList.addAll(getFollowUpOrderList);
                }
                
            } 
        }
        else{
            getOrderList.addAll(getFollowUpOrderList);
        }
        
        return getOrderList;
    } 
    
    public static List<Order__c> selectedOrderDetails(String orderId)
    {
        
        return [SELECT Id,CreatedDate, Name, Status__c,FollowUp_Stage__c,Payment_Status__c,Call__c, isVerified__c, Order_Delivery_Status__c, 
                Total_Price__c, Grand_Total__c, Order_Amount__c, Account__r.Name, Account__r.Phone__c, Next_FollowUp_Time__c, 
                Billing_Street__c, Billing_City__c, Billing_State__c, Billing_PostalCode__c, Billing_Country__c, 
                Shipping_Street__c, Shipping_City__c, Shipping_State__c, Shipping_PostalCode__c, Shipping_Country__c
                FROM Order__c where Id =: orderId LIMIT 1];
    }
    
    //For status change on click of Voided Button
    @AuraEnabled
    public static void voidOrder(Id orderId) {
        List<Order__c> orderList = [SELECT Id, Status__c, FollowUp_Stage__c FROM Order__c WHERE Id = :orderId];
        List<Order__c> updOrdLst = new List<Order__c>();
        if (orderList.Size() > 0) {
            for(Order__c ord : orderList){
                ord.Status__c = 'Voided';
                ord.FollowUp_Stage__c = 'No Stage';
                updOrdLst.add(ord);
            }
            update orderList;
        }
    }
}