force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>CDLOrder</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/FollowUp_Stage__c.field-meta.xml
<CustomField>
    <fullName>FollowUp_Stage__c</fullName>
    <label>FollowUp Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manifest</fullName>
                <default>true</default>
                <label>Manifest</label>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>NDR</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>No Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Last_Delivery_Status_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Delivery_Status_Change_Date__c</fullName>
    <label>Last Delivery Status Change Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Next_FollowUp_Time__c.field-meta.xml
<CustomField>
    <fullName>Next_FollowUp_Time__c</fullName>
    <label>Next FollowUp Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Delivery_Status__c</fullName>
    <label>Order Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>PENDING PICKUP</fullName>
            </value>
            <value>
                <fullName>picked up</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Manifest</fullName>
                <default>true</default>
                <label>Manifest</label>
            </value>
            <value>
                <fullName>in transit</fullName>
            </value>
            <value>
                <fullName>undelivered</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>PICKUP DONE</fullName>
            </value>
            <value>
                <fullName>picked up1</fullName>
            </value>
            <value>
                <fullName>INTRANSIT</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>NDR</fullName>
            </value>
            <value>
                <fullName>Confirmed Orders of Shopify</fullName>
            </value>
            <value>
                <fullName>rto in transit</fullName>
            </value>
            <value>
                <fullName>shortage</fullName>
            </value>
            <value>
                <fullName>rto processing</fullName>
            </value>
            <value>
                <fullName>reached at origin</fullName>
            </value>
            <value>
                <fullName>rto delivered</fullName>
            </value>
            <value>
                <fullName>misrouted</fullName>
            </value>
            <value>
                <fullName>rto out for delivery</fullName>
            </value>
            <value>
                <fullName>out of delivery area</fullName>
            </value>
            <value>
                <fullName>rto undelivered</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <externalId>true</externalId>
    <label>Order Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
                <default>true</default>
                <label>Confirm</label>
            </value>
            <value>
                <fullName>voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Track_Id__c.field-meta.xml
<CustomField>
    <fullName>Track_Id__c</fullName>
    <label>Tracking Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order_Follow_Up__c/Order_Follow_Up__c.object-meta.xml
<CustomObject>
    <label>Order Follow Up</label>
    <nameField>
        <displayFormat>FU - {0000}</displayFormat>
        <label>Order Follow Up  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Follow Ups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Follow_Up__c/fields/FollowUp_Stage__c.field-meta.xml
<CustomField>
    <fullName>FollowUp_Stage__c</fullName>
    <label>FollowUp Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>NDR</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>in transit</fullName>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>Manifest</fullName>
                <default>true</default>
                <label>Manifest</label>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Follow_Up__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Follow Ups</relationshipLabel>
    <relationshipName>Order_Follow_Ups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Follow_Up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>On Time</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CDL_NextFolloupBatchTest.cls
@isTest
public class CDL_NextFolloupBatchTest {

    @isTest
    static void testGetAbandonedCheckoutsQueue() 
    {
        Account acc = new Account();
        acc.Name = 'Test 31';
        Insert acc;
        
        Account acc1 = new Account();
        acc1.Name = 'Test 31';
        Insert acc1;
        
        Order__c createOrder = new Order__c();
        createOrder.Order_Id__c = 'Test123';
        createOrder.Name = 'Test Order';
        createOrder.Status__c = 'Abandoned';
        createOrder.Track_Id__c = '77801128915';
        createOrder.Order_Delivery_Status__c = 'Manifest';
        createOrder.FollowUp_Stage__c = 'Manifest';
        createOrder.Account__c = acc.Id;
        createOrder.Next_FollowUp_Time__c =System.now().addhours(-24);
        createOrder.Last_Delivery_Status_Change_Date__c=System.now().addhours(-30);
        insert createOrder;

        Order__c createOrder1 = new Order__c();
        createOrder1.Order_Id__c = 'Test1233';
        createOrder1.Name = 'Test Order3';
        createOrder1.Status__c = 'Abandoned';
        createOrder1.Track_Id__c = '778011289315';
        createOrder1.Order_Delivery_Status__c = 'IN_PROGRESS';
        createOrder1.Account__c = acc1.Id;
        createOrder1.Note__c = 'testttt';
        insert createOrder1;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        
        User u = new User(Alias = 'standt32', Email='standarduser@testorg.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles', UserName='standardusercdlfineshine@testorg.com');
        insert u;
        
        Order_Follow_Up__c OrderFollow = new Order_Follow_Up__c();
        OrderFollow.Order__c = createOrder.Id;
        OrderFollow.Status__c = 'Pending';
        insert OrderFollow;
        
        
     	Test.startTest();
        Datetime now = Datetime.now();
        Datetime nextRunTime = now.addMinutes(15);
        String cronExp = '' + nextRunTime.second() + ' ' + nextRunTime.minute() + ' ' + nextRunTime.hour() + ' ' + nextRunTime.day() + ' ' + nextRunTime.month() + ' ? ' + nextRunTime.year();
        CDL_NextFolloupBatchSchedulable orderStatus = new CDL_NextFolloupBatchSchedulable();
        String jobIDsendmail = System.schedule('CDL NextFolloupUp Batch',cronExp, orderStatus);
        Test.StopTest();
        
        
        
    }
}